# Generated by Django 3.1.13 on 2022-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERC20Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=256, verbose_name='地址')),
                ('name', models.CharField(default=None, max_length=512, verbose_name='名称')),
                ('symbol', models.CharField(default=None, max_length=128, verbose_name='符号')),
                ('decimals', models.SmallIntegerField(default=0, verbose_name='小数位数')),
                ('net_work', models.CharField(default='', max_length=32, verbose_name='链名称')),
            ],
        ),
        migrations.CreateModel(
            name='PairInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=None, verbose_name='下标')),
                ('address', models.CharField(default='', max_length=256, verbose_name='地址')),
                ('token0', models.CharField(default='', max_length=256, verbose_name='token0地址')),
                ('token1', models.CharField(default='', max_length=256, verbose_name='token1地址')),
                ('net_work', models.CharField(default='', max_length=32, verbose_name='链名称')),
            ],
        ),
    ]
